version: '3'
networks:
  idealinvest-network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.18.1.0/24
services:
  backoffice:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $BACKOFFICE_LOCAL:$BACKOFFICE_DOCKER
      - $CDN_LOCAL:$CDN_DOCKER
    build:
      dockerfile: ./DockerFiles/Backoffice/Dockerfile
      context: .
    container_name: backoffice
    image: idealinvest/backoffice
    extra_hosts:
      - "$BACKOFFICE_URL:127.0.0.1"
      - "$BACKOFFICE_API_URL:127.0.0.1"
      - "$APIPRAVALER_URL:$APIPRAVALER_IP"
      - "$APIAPARTADA_URL:$APIAPARTADA_IP"
    environment:
      - SITE_HOST=$BACKOFFICE_URL
      - SITE_DOCUMENT_ROOT=$BACKOFFICE_DOCUMENT_ROOT
      - VOLUME=$BACKOFFICE_DOCKER
      - CDN=$CDN_DOCKER
      - API_HOST=$BACKOFFICE_API_URL
      - API_DOCUMENT_ROOT=$BACKOFFICE_API_DOCUMENT_ROOT
    networks:
      idealinvest-network:
        ipv4_address: $BACKOFFICE_IP
  portal_pravaler:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $PORTALPRAVALER_LOCAL:$PORTALPRAVALER_DOCKER
    container_name: portal_pravaler
    image: kaioidealinvest/php:5.6
    extra_hosts:
      - "$PORTALPRAVALER_URL:127.0.0.1"
      - "$BACKOFFICE_URL:$BACKOFFICE_IP"
      - "$BACKOFFICE_API_URL:$BACKOFFICE_IP"
      - "$APIAPARTADA_URL:$APIAPARTADA_IP"
      - "qa.marketplace.idealinvest.srv.br:10.10.100.177"
    depends_on:
      - backoffice
    networks:
      idealinvest-network:
        ipv4_address: $PORTALPRAVALER_IP
    environment:
      - VOLUME=$PORTALPRAVALER_DOCKER
      - SITE_HOST=$PORTALPRAVALER_URL
      - SITE_DOCUMENT_ROOT=$PORTALPRAVALER_DOCUMENT_ROOT
  api_pravaler:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $APIPRAVALER_LOCAL:$APIPRAVALER_DOCKER
    container_name: api_pravaler
    image: kaioidealinvest/php:7.1
    extra_hosts:
      - "$APIPRAVALER_URL:127.0.0.1"
    environment:
      - VOLUME=$APIPRAVALER_DOCKER
      - SITE_HOST=$APIPRAVALER_URL
      - SITE_DOCUMENT_ROOT=$APIPRAVALER_DOCUMENT_ROOT
    networks:
      idealinvest-network:
        ipv4_address: $APIPRAVALER_IP
  api_apartada:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $APIAPARTADA_LOCAL:$APIAPARTADA_DOCKER
      - $BACKOFFICE_LOCAL:$BACKOFFICE_DOCKER
    container_name: api_apartada
    image: kaioidealinvest/php:5.6
    extra_hosts:
      - "$APIAPARTADA_URL:127.0.0.1"
    environment:
      - VOLUME=$APIAPARTADA_DOCKER
      - SITE_HOST=$APIAPARTADA_URL
      - SITE_DOCUMENT_ROOT=$APIAPARTADA_DOCUMENT_ROOT
    networks:
      idealinvest-network:
        ipv4_address: $APIAPARTADA_IP
  creditscore:
    volumes:
      - $CREDITSCORE_LOCAL:$CREDITSCORE_DOCKER
    build:
      dockerfile: ./DockerFiles/CreditScore/Dockerfile
      context: .
    container_name: creditscore
    image: kaioidealinvest/php:7.1
    extra_hosts:
      - "$CREDITSCORE_URL:127.0.0.1"
    environment:
      - VOLUME=$CREDITSCORE_DOCKER
      - SITE_HOST=$CREDITSCORE_URL
      - SITE_DOCUMENT_ROOT=$CREDITSCORE_DOCUMENT_ROOT
    networks:
      idealinvest-network:
        ipv4_address: $CREDITSCORE_IP
  agendamento:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $AGENDAMENTO_LOCAL:$AGENDAMENTO_DOCKER
      - $BACKOFFICE_LOCAL:$BACKOFFICE_DOCKER
    container_name: agendamento
    image: kaioidealinvest/php:7.1
    extra_hosts:
      - "$AGENDAMENTO_URL:127.0.0.1"
    environment:
      - VOLUME=$AGENDAMENTO_DOCKER
      - SITE_HOST=$AGENDAMENTO_URL
      - SITE_DOCUMENT_ROOT=$AGENDAMENTO_DOCUMENT_ROOT
    networks:
      idealinvest-network:
        ipv4_address: $AGENDAMENTO_IP
  nova_proposta_backend:
    volumes:
      - $NOVAPROPOSTA_BACKEND_LOCAL:$NOVAPROPOSTA_BACKEND_DOCKER
    container_name: nova_proposta_backend
    image: kaioidealinvest/php:7.1
    extra_hosts:
      - "$NOVAPROPOSTA_BACKEND_URL:127.0.0.1"
      - "$BACKOFFICE_URL:$BACKOFFICE_IP"
      - "$BACKOFFICE_API_URL:$BACKOFFICE_IP"
      - "$APIAPARTADA_URL:$APIAPARTADA_IP"
      - "$CREDITSCORE_URL:$CREDITSCORE_IP"
    environment:
      - VOLUME=$NOVAPROPOSTA_BACKEND_DOCKER
      - SITE_HOST=$NOVAPROPOSTA_BACKEND_URL
      - SITE_DOCUMENT_ROOT=$NOVAPROPOSTA_BACKEND_DOCUMENT_ROOT
    networks:
      idealinvest-network:
        ipv4_address: $NOVAPROPOSTA_BACKEND_IP
    depends_on:
      - mongo_db
      - rabbitmq
  nova_proposta_frontend:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $NOVAPROPOSTAFRONTEND_LOCAL:$NOVAPROPOSTAFRONTEND_DOCKER
    build:
      dockerfile: ./DockerFiles/NovaPropostaFrontEnd/Dockerfile
      context: .
    container_name: nova_proposta_frontend
    extra_hosts:
      - "$NOVAPROPOSTAFRONTEND_URL:127.0.0.1"
    environment:
      - NOVAPROPOSTABACKEND_URL=$NOVAPROPOSTABACKEND_URL
      - APIPRAVALER_URL=$APIPRAVALER_URL
    networks:
      idealinvest-network:
        ipv4_address: $NOVAPROPOSTAFRONTEND_IP
  nginx:
    restart: always
    stdin_open: true
    tty: true
    build:
      dockerfile: ./DockerFiles/Nginx/Dockerfile
      context: .
    container_name: nginx
    image: idealinvest/nginx
    ports:
      - "80:80"
      - "9000:9000"
    networks:
      idealinvest-network:
        ipv4_address: $NGINX_IP
    depends_on:
      - backoffice
  mongo_db:
    restart: always
    stdin_open: true
    tty: true
    image: mongo:latest
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=novaproposta
      - MONGO_INITDB_ROOT_PASSWORD=novaproposta
      - MONGO_INITDB_DATABASE=proposta
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/db
    networks:
      idealinvest-network:
        ipv4_address: $MONGO_IP
  rabbitmq:
    stdin_open: true
    tty: true
    image: rabbitmq:3
    restart: always
    networks:
      idealinvest-network:
        ipv4_address: $RABBITMQ_IP
    environment:
      - RABBITMQ_ERLANG_COOKIE=9143a224982c82ae6985f3735bc95407
      - RABBITMQ_NODENAME=proposta-nova-node-1
  rabbitmq_management:
    stdin_open: true
    tty: true
    image: rabbitmq:3-management
    restart: always
    networks:
      idealinvest-network:
        ipv4_address: $RABBITMQ_MANAGEMENT_IP
    environment:
      - RABBITMQ_DEFAULT_VHOST=rabbitmq
      - RABBITMQ_DEFAULT_USER=propostanova
      - RABBITMQ_DEFAULT_PASS=propostanova
    depends_on:
      - rabbitmq