version: '3'
networks:
  idealinvest-network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.18.1.0/24
services:
  backoffice:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $BACKOFFICE_LOCAL:$BACKOFFICE_DOCKER
    build:
      dockerfile: ./DockerFiles/Backoffice/Dockerfile
      context: .
    image: kaioidealinvest/backoffice
    container_name: backoffice
    extra_hosts:
      - "$BACKOFFICE_URL:127.0.0.1"
      - "$BACKOFFICE_API_URL:127.0.0.1"
      - "$APIPRAVALER_URL:$APIPRAVALER_IP"
      - "$APIAPARTADA_URL:$APIAPARTADA_IP"
      - "$FTPRISCOCOBRANCA_URL:$FTPRISCOCOBRANCA_IP"
      - "$CDN_URL:$CDN_IP"
      - "retornomec.idealinvest.srv.br:10.104.110.143"
      - "$SEGUROS_URL:$SEGUROS_IP"
    environment:
      - SITE_HOST=$BACKOFFICE_URL
      - SITE_DOCUMENT_ROOT=$BACKOFFICE_DOCUMENT_ROOT
      - VOLUME=$BACKOFFICE_DOCKER
      - CDN_URL=$CDN_URL
      - API_HOST=$BACKOFFICE_API_URL
      - API_DOCUMENT_ROOT=$BACKOFFICE_API_DOCUMENT_ROOT
    networks:
      idealinvest-network:
        ipv4_address: $BACKOFFICE_IP
  cdn:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $CDN_LOCAL:$CDN_DOCKER
    image: kaioidealinvest/apache:ubuntu16.04
    container_name: cdn
    extra_hosts:
      - "$CDN_URL:127.0.0.1"
    environment:
      - SITE_HOST=$CDN_URL
      - SITE_DOCUMENT_ROOT=$CDN_DOCUMENT_ROOT
      - VOLUME=$CDN_DOCKER
    networks:
      idealinvest-network:
        ipv4_address: $CDN_IP
  portal_pravaler:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $PORTALPRAVALER_LOCAL:$PORTALPRAVALER_DOCKER
    container_name: portal_pravaler
    image: kaioidealinvest/php:5.6
    extra_hosts:
      - "$PORTALPRAVALER_URL:127.0.0.1"
      - "$BACKOFFICE_URL:$BACKOFFICE_IP"
      - "$BACKOFFICE_API_URL:$BACKOFFICE_IP"
      - "$APIAPARTADA_URL:$APIAPARTADA_IP"
      - "qa.marketplace.idealinvest.srv.br:10.10.100.177"
      - "$SEGUROS_URL:$SEGUROS_IP"
    depends_on:
      - backoffice
    networks:
      idealinvest-network:
        ipv4_address: $PORTALPRAVALER_IP
    environment:
      - VOLUME=$PORTALPRAVALER_DOCKER
      - SITE_HOST=$PORTALPRAVALER_URL
      - SITE_DOCUMENT_ROOT=$PORTALPRAVALER_DOCUMENT_ROOT
  api_pravaler:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $APIPRAVALER_LOCAL:$APIPRAVALER_DOCKER
    container_name: api_pravaler
    image: kaioidealinvest/php:7.0
    extra_hosts:
      - "$APIPRAVALER_URL:127.0.0.1"
    environment:
      - VOLUME=$APIPRAVALER_DOCKER
      - SITE_HOST=$APIPRAVALER_URL
      - SITE_DOCUMENT_ROOT=$APIPRAVALER_DOCUMENT_ROOT
    networks:
      idealinvest-network:
        ipv4_address: $APIPRAVALER_IP
  api_apartada:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $APIAPARTADA_LOCAL:$APIAPARTADA_DOCKER
      - $BACKOFFICE_LOCAL:$BACKOFFICE_DOCKER
    container_name: api_apartada
    image: kaioidealinvest/php:5.6
    extra_hosts:
      - "$APIAPARTADA_URL:127.0.0.1"
    environment:
      - VOLUME=$APIAPARTADA_DOCKER
      - SITE_HOST=$APIAPARTADA_URL
      - SITE_DOCUMENT_ROOT=$APIAPARTADA_DOCUMENT_ROOT
    networks:
      idealinvest-network:
        ipv4_address: $APIAPARTADA_IP
  creditscore:
    volumes:
      - $CREDITSCORE_LOCAL:$CREDITSCORE_DOCKER
    build:
      dockerfile: ./DockerFiles/CreditScore/Dockerfile
      context: .
    container_name: creditscore
    image: kaioidealinvest/php:7.1
    extra_hosts:
      - "$CREDITSCORE_URL:127.0.0.1"
    environment:
      - VOLUME=$CREDITSCORE_DOCKER
      - SITE_HOST=$CREDITSCORE_URL
      - SITE_DOCUMENT_ROOT=$CREDITSCORE_DOCUMENT_ROOT
    networks:
      idealinvest-network:
        ipv4_address: $CREDITSCORE_IP
  agendamento:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $AGENDAMENTO_LOCAL:$AGENDAMENTO_DOCKER
      - $BACKOFFICE_LOCAL:$BACKOFFICE_DOCKER
    container_name: agendamento
    image: kaioidealinvest/php:7.1
    extra_hosts:
      - "$AGENDAMENTO_URL:127.0.0.1"
    environment:
      - VOLUME=$AGENDAMENTO_DOCKER
      - SITE_HOST=$AGENDAMENTO_URL
      - SITE_DOCUMENT_ROOT=$AGENDAMENTO_DOCUMENT_ROOT
    networks:
      idealinvest-network:
        ipv4_address: $AGENDAMENTO_IP
  nginx:
    restart: always
    stdin_open: true
    tty: true
    build:
      dockerfile: ./DockerFiles/Nginx/Dockerfile
      context: .
    container_name: nginx
    image: kaioidealinvest/nginx
    ports:
      - "80:80"
      - "9000:9000"
    networks:
      idealinvest-network:
        ipv4_address: $NGINX_IP
  mongodb:
    container_name: mongodb
    image: mongo:3.4
    restart: always
    networks:
       idealinvest-network:
          ipv4_address: $MONGO_IP
  mongo-temp:
    container_name: mongo-temp
    build:
      dockerfile: ./DockerFiles/MongoDB/Dockerfile
      context: .
    restart: always
    image: kaioidealinvest/mongo-temp
    networks:
      idealinvest-network:
        ipv4_address: $MONGO_TEMP_IP
    command: mongo "mongodb://$MONGO_IP" /data/db/script.js
    depends_on:
      - mongodb
  nova_proposta_frontend:
    stdin_open: true
    tty: true
    container_name: nova_proposta_frontend
    volumes:
      - $NOVAPROPOSTA_FRONTEND_LOCAL:$NOVAPROPOSTA_FRONTEND_DOCKER
    build:
      dockerfile: ./DockerFiles/NovaPropostaFrontEnd/Dockerfile
      context: .
    container_name: nova_proposta_frontend
    image: kaioidealinvest/nova_proposta_frontend
    extra_hosts:
      - "$NOVAPROPOSTA_FRONTEND_URL:127.0.0.1"
      - "$NOVAPROPOSTA_BACKEND_URL:$NOVAPROPOSTA_BACKEND_IP"
    environment:
      - VOLUME=$NOVAPROPOSTA_BACKEND_DOCKER
      - NOVAPROPOSTA_BACKEND_URL=$NOVAPROPOSTA_BACKEND_URL
      - APIPRAVALER_URL=$APIPRAVALER_URL
      - SITE_HOST=$NOVAPROPOSTA_FRONTEND_URL
    networks:
      idealinvest-network:
        ipv4_address: $NOVAPROPOSTA_FRONTEND_IP
  nova_proposta_backend:
    restart: always
    container_name: nova_proposta_backend
    image: kaioidealinvest/php:7.0
    stdin_open: true
    tty: true
    environment:
      - VOLUME=$NOVAPROPOSTA_BACKEND_DOCKER
      - SITE_HOST=$NOVAPROPOSTA_BACKEND_URL
      - SITE_DOCUMENT_ROOT=$NOVAPROPOSTA_BACKEND_DOCUMENT_ROOT
    volumes:
      - $NOVAPROPOSTA_BACKEND_LOCAL:$NOVAPROPOSTA_BACKEND_DOCKER
    extra_hosts:
      - "$NOVAPROPOSTA_BACKEND_URL:127.0.0.1"
      - "$BACKOFFICE_URL:$BACKOFFICE_IP"
      - "$APIAPARTADA_URL:$APIAPARTADA_IP"
      - "$APIPRAVALER_URL:$APIPRAVALER_IP"
      - "$CREDITSCORE_URL:$CREDITSCORE_IP"
      - "$NOVAPROPOSTA_FRONTEND_URL:$NOVAPROPOSTA_FRONTEND_IP"
    networks:
       idealinvest-network:
          ipv4_address: $NOVAPROPOSTA_BACKEND_IP
    depends_on:
      - "mongo-temp"
      - "rabbitmq"
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    restart: always
    networks:
      idealinvest-network:
        ipv4_address: $RABBITMQ_IP
    environment:
      - RABBITMQ_ERLANG_COOKIE=9143a224982c82ae6985f3735bc95407
      - RABBITMQ_NODENAME=proposta-nova-node-1
  rabbitmq-management:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq-management
    networks:
      idealinvest-network:
        ipv4_address: $RABBITMQ_MANAGEMENT_IP
    environment:
      - RABBITMQ_DEFAULT_VHOST=cadastro.rabbitmq.desenv
      - RABBITMQ_DEFAULT_USER=propostanova
      - RABBITMQ_DEFAULT_PASS=propostanova
    depends_on:
     - "rabbitmq"
  ftp-risco-cobranca:
    restart: always
    build:
      dockerfile: ./DockerFiles/FtpRiscoCobranca/Dockerfile
      context: .
    container_name: ftp-risco-cobranca
    image: kaioidealinvest/ftp-risco-cobranca
    stdin_open: true
    volumes:
      - "/home/ftpusers/"
      - "/etc/pure-ftpd/passwd"
    environment:
      - PUBLICHOST=localhost
      - FTPRISCOCOBRANCA_BOLETOAVULSO_USER=$FTPRISCOCOBRANCA_BOLETOAVULSO_USER
      - FTPRISCOCOBRANCA_BOLETOAVULSO_PASSWORD=$FTPRISCOCOBRANCA_BOLETOAVULSO_PASSWORD
      - FTPRISCOCOBRANCA_IMPORTACAO_USER=$FTPRISCOCOBRANCA_IMPORTACAO_USER
      - FTPRISCOCOBRANCA_IMPORTACAO_PASSWORD=$FTPRISCOCOBRANCA_IMPORTACAO_PASSWORD
    tty: true
    networks:
      idealinvest-network:
        ipv4_address: $FTPRISCOCOBRANCA_IP
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
  seguros:
    restart: always
    container_name: seguros
    image: kaioidealinvest/php:7.0
    stdin_open: true
    tty: true
    environment:
      - VOLUME=$SEGUROS_DOCKER
      - SITE_HOST=$SEGUROS_URL
      - SITE_DOCUMENT_ROOT=$SEGUROS_DOCUMENT_ROOT
    volumes:
      - $SEGUROS_LOCAL:$SEGUROS_DOCKER
    extra_hosts:
      - "$SEGUROS_URL:127.0.0.1"
      - "$BACKOFFICE_URL:$BACKOFFICE_IP"
      - "$PORTALPRAVALER_URL:$PORTALPRAVALER_IP"
    networks:
       idealinvest-network:
          ipv4_address: $SEGUROS_IP
