version: '3'
networks:
  default:
    external:
      name: Pravaler
services:
  negotiation:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_NEGOTIATION_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaioidealinvest/neo:php7.2
    container_name: $NEO_NEGOTIATION_PROJECT
    extra_hosts:
          - "$NEO_NEGOTIATION_URL:127.0.0.1"
    environment:
      - ROOT=$NEO_NEGOTIATION_ROOT
      - URL=$NEO_NEGOTIATION_URL
      - VOLUME=$NEO_SERVICE_VOLUME
    networks:
      default:
        ipv4_address: $NEO_NEGOTIATION_IP
        aliases:
          - $NEO_NEGOTIATION_URL
  proposal:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_PROPOSAL_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaioidealinvest/neo:php7.2
    container_name: $NEO_PROPOSAL_PROJECT
    extra_hosts:
          - "$NEO_PROPOSAL_URL:127.0.0.1"
    environment:
      - ROOT=$NEO_PROPOSAL_ROOT
      - URL=$NEO_PROPOSAL_URL
      - VOLUME=$NEO_SERVICE_VOLUME
    networks:
      default:
        ipv4_address: $NEO_PROPOSAL_IP
        aliases:
          - $NEO_PROPOSAL_URL
  integration:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_INTEGRATION_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaioidealinvest/neo:php7.2
    container_name: $NEO_INTEGRATION_PROJECT
    extra_hosts:
          - "$NEO_INTEGRATION_URL:127.0.0.1"
    environment:
      - ROOT=$NEO_INTEGRATION_ROOT
      - URL=$NEO_INTEGRATION_URL
      - VOLUME=$NEO_SERVICE_VOLUME
    networks:
      default:
        ipv4_address: $NEO_INTEGRATION_IP
        aliases:
          - $NEO_INTEGRATION_URL
  student:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_STUDENT_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaioidealinvest/neo:php7.2
    container_name: $NEO_STUDENT_PROJECT
    extra_hosts:
          - "$NEO_STUDENT_URL:127.0.0.1"
    environment:
      - ROOT=$NEO_STUDENT_ROOT
      - URL=$NEO_STUDENT_URL
      - VOLUME=$NEO_SERVICE_VOLUME
    networks:
      default:
        ipv4_address: $NEO_STUDENT_IP
        aliases:
          - $NEO_STUDENT_URL
  callcenter:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $ALFRED_SERVER_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaioidealinvest/neo:php7.2
    container_name: $ALFRED_SERVER_PROJECT
    extra_hosts:
          - "$ALFRED_SERVER_URL:127.0.0.1"
    environment:
      - ROOT=$ALFRED_SERVER_ROOT
      - URL=$ALFRED_SERVER_URL
      - VOLUME=$NEO_SERVICE_VOLUME
    networks:
      default:
        ipv4_address: $ALFRED_SERVER_IP
        aliases:
          - $ALFRED_SERVER_URL
  alfred-client:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $ALFRED_CLIENT_LOCAL:$ALFRED_CLIENT_DOCKER
    build:
      dockerfile: ./DockerFiles/Neo/AlfredClient/Dockerfile
      context: .
    container_name: alfred-client
    image: kaioidealinvest/alfred_client
    extra_hosts:
      - "$ALFRED_CLIENT_URL:127.0.0.1"
    environment:
      - SITE_HOST=$ALFRED_CLIENT_URL
      - PROJECT_FOLDER=$ALFRED_CLIENT_DOCKER
    networks:
      default:
        ipv4_address: $ALFRED_CLIENT_IP
        aliases:
          - $ALFRED_CLIENT_URL
  log:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_LOG_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaioidealinvest/neo:php7.2
    container_name: $NEO_LOG_PROJECT
    extra_hosts:
          - "$NEO_LOG_URL:127.0.0.1"
    environment:
      - ROOT=$NEO_LOG_ROOT
      - URL=$NEO_LOG_URL
      - VOLUME=$NEO_SERVICE_VOLUME
    networks:
      default:
        ipv4_address: $NEO_LOG_IP
        aliases:
          - $NEO_LOG_URL
  neo-api:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_API_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaioidealinvest/neo:php7.2
    container_name: $NEO_API_PROJECT
    extra_hosts:
          - "$NEO_API_URL:127.0.0.1"
    environment:
      - ROOT=$NEO_API_ROOT
      - URL=$NEO_API_URL
      - VOLUME=$NEO_SERVICE_VOLUME
    networks:
      default:
        ipv4_address: $NEO_API_IP
        aliases:
          - $NEO_API_URL