version: '3'
networks:
  default:
    external:
      name: Pravaler
services:
  negotiation:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_NEGOTIATION_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaiocarvalhopravaler/neo:php7.2-nginx
    container_name: $NEO_NEGOTIATION_CONTAINER
    extra_hosts:
          - "$NEO_NEGOTIATION_URL:127.0.0.1"
    environment:
      - ROOT=${NEO_SERVICE_VOLUME}${NEO_NEGOTIATION_ROOT}
      - URL=$NEO_NEGOTIATION_URL
      - VOLUME=$NEO_SERVICE_VOLUME
      - CONTAINER=$NEO_NEGOTIATION_CONTAINER
      - REMOTE_HOST=$HOST_IP
    networks:
      default:
        ipv4_address: $NEO_NEGOTIATION_IP
        aliases:
          - $NEO_NEGOTIATION_URL
  proposal:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_PROPOSAL_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaiocarvalhopravaler/neo:php7.2-nginx
    container_name: $NEO_PROPOSAL_CONTAINER
    extra_hosts:
          - "$NEO_PROPOSAL_URL:127.0.0.1"
    environment:
      - ROOT=${NEO_SERVICE_VOLUME}${NEO_PROPOSAL_ROOT}
      - URL=$NEO_PROPOSAL_URL
      - VOLUME=$NEO_SERVICE_VOLUME
      - CONTAINER=$NEO_PROPOSAL_CONTAINER
      - REMOTE_HOST=$HOST_IP
    networks:
      default:
        ipv4_address: $NEO_PROPOSAL_IP
        aliases:
          - $NEO_PROPOSAL_URL
  integration:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_INTEGRATION_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaiocarvalhopravaler/neo:php7.2-nginx
    container_name: $NEO_INTEGRATION_CONTAINER
    extra_hosts:
          - "$NEO_INTEGRATION_URL:127.0.0.1"
    environment:
      - ROOT=${NEO_SERVICE_VOLUME}${NEO_INTEGRATION_ROOT}
      - URL=$NEO_INTEGRATION_URL
      - VOLUME=$NEO_SERVICE_VOLUME
      - CONTAINER=$NEO_INTEGRATION_CONTAINER
      - REMOTE_HOST=$HOST_IP
    networks:
      default:
        ipv4_address: $NEO_INTEGRATION_IP
        aliases:
          - $NEO_INTEGRATION_URL
  student:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_STUDENT_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaiocarvalhopravaler/neo:php7.2-nginx
    container_name: $NEO_STUDENT_CONTAINER
    extra_hosts:
          - "$NEO_STUDENT_URL:127.0.0.1"
    environment:
      - ROOT=${NEO_SERVICE_VOLUME}${NEO_STUDENT_ROOT}
      - URL=$NEO_STUDENT_URL
      - VOLUME=$NEO_SERVICE_VOLUME
      - CONTAINER=$NEO_STUDENT_CONTAINER
      - REMOTE_HOST=$HOST_IP
    networks:
      default:
        ipv4_address: $NEO_STUDENT_IP
        aliases:
          - $NEO_STUDENT_URL
  callcenter:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $ALFRED_SERVER_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaiocarvalhopravaler/neo:php7.2-nginx
    container_name: $ALFRED_SERVER_CONTAINER
    extra_hosts:
          - "$ALFRED_SERVER_URL:127.0.0.1"
    environment:
      - ROOT=${NEO_SERVICE_VOLUME}${ALFRED_SERVER_ROOT}
      - URL=$ALFRED_SERVER_URL
      - VOLUME=$NEO_SERVICE_VOLUME
      - CONTAINER=$ALFRED_SERVER_CONTAINER
      - REMOTE_HOST=$HOST_IP
    networks:
      default:
        ipv4_address: $ALFRED_SERVER_IP
        aliases:
          - $ALFRED_SERVER_URL
  alfred_client:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $ALFRED_CLIENT_LOCAL:$ALFRED_CLIENT_DOCKER
    container_name: $ALFRED_CLIENT_CONTAINER
    image: kaiocarvalhopravaler/angular:node-9
    extra_hosts:
      - "$ALFRED_CLIENT_URL:127.0.0.1"
    environment:
      - VOLUME=$ALFRED_CLIENT_DOCKER
      - ENVIRONMENT=integration
      - DOCUMENT_ROOT=/
    networks:
      default:
        ipv4_address: $ALFRED_CLIENT_IP
        aliases:
          - $ALFRED_CLIENT_URL
  neo_log:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_LOG_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaiocarvalhopravaler/neo:php7.2-nginx
    container_name: $NEO_LOG_CONTAINER
    extra_hosts:
          - "$NEO_LOG_URL:127.0.0.1"
    environment:
      - ROOT=${NEO_SERVICE_VOLUME}${NEO_LOG_ROOT}
      - URL=$NEO_LOG_URL
      - VOLUME=$NEO_SERVICE_VOLUME
      - CONTAINER=$NEO_LOG_CONTAINER
      - REMOTE_HOST=$HOST_IP
    networks:
      default:
        ipv4_address: $NEO_LOG_IP
        aliases:
          - $NEO_LOG_URL
  neo_api:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_API_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaiocarvalhopravaler/neo:php7.2-nginx
    container_name: $NEO_API_CONTAINER
    extra_hosts:
          - "$NEO_API_URL:127.0.0.1"
    environment:
      - ROOT=${NEO_SERVICE_VOLUME}${NEO_API_ROOT}
      - URL=$NEO_API_URL
      - VOLUME=$NEO_SERVICE_VOLUME
      - CONTAINER=$NEO_API_CONTAINER
      - REMOTE_HOST=$HOST_IP
    networks:
      default:
        ipv4_address: $NEO_API_IP
        aliases:
          - $NEO_API_URL
  oauth:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_OAUTH_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaiocarvalhopravaler/neo:php7.2-nginx
    container_name: $NEO_OAUTH_CONTAINER
    extra_hosts:
          - "$NEO_OAUTH_URL:127.0.0.1"
    environment:
      - ROOT=${NEO_SERVICE_VOLUME}${NEO_OAUTH_ROOT}
      - URL=$NEO_OAUTH_URL
      - VOLUME=$NEO_SERVICE_VOLUME
      - INDEX=$NEO_OAUTH_INDEX
      - CONTAINER=$NEO_OAUTH_CONTAINER
      - REMOTE_HOST=$HOST_IP
    networks:
      default:
        ipv4_address: $NEO_OAUTH_IP
        aliases:
          - $NEO_OAUTH_URL
  bpm:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_BPM_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaiocarvalhopravaler/neo:php7.2-nginx
    container_name: $NEO_BPM_CONTAINER
    extra_hosts:
          - "$NEO_BPM_URL:127.0.0.1"
    environment:
      - ROOT=${NEO_SERVICE_VOLUME}${NEO_BPM_ROOT}
      - URL=$NEO_BPM_URL
      - VOLUME=$NEO_SERVICE_VOLUME
      - CONTAINER=$NEO_OAUTH_CONTAINER
      - REMOTE_HOST=$HOST_IP
    networks:
      default:
        ipv4_address: $NEO_BPM_IP
        aliases:
          - $NEO_BPM_URL
  people:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $NEO_PEOPLE_LOCAL:$NEO_SERVICE_VOLUME
      - $NEO_CONFIG:/opt/neo/config.php
    image: kaiocarvalhopravaler/neo:php7.2-nginx
    container_name: $NEO_PEOPLE_CONTAINER
    extra_hosts:
          - "$NEO_PEOPLE_URL:127.0.0.1"
    environment:
      - ROOT=${NEO_SERVICE_VOLUME}${NEO_PEOPLE_ROOT}
      - URL=$NEO_PEOPLE_URL
      - VOLUME=$NEO_SERVICE_VOLUME
      - CONTAINER=$NEO_OAUTH_CONTAINER
      - REMOTE_HOST=$HOST_IP
    networks:
      default:
        ipv4_address: $NEO_PEOPLE_IP
        aliases:
          - $NEO_PEOPLE_URL