version: '3'
networks:
  default:
    external:
      name: Pravaler
services:
  backoffice:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $BACKOFFICE_LOCAL:$BACKOFFICE_DOCKER
    build:
      dockerfile: ./DockerFiles/Backoffice/Dockerfile
      context: .
    container_name: $BACKOFFICE_CONTAINER
    extra_hosts:
      - "$BACKOFFICE_URL:127.0.0.1"
      - "$BACKOFFICE_API_URL:127.0.0.1"
    environment:
      - SITE_HOST=$BACKOFFICE_URL
      - SITE_DOCUMENT_ROOT=${BACKOFFICE_DOCKER}${BACKOFFICE_DOCUMENT_ROOT}
      - VOLUME=$BACKOFFICE_DOCKER
      - CDN_URL=$CDN_URL
      - API_HOST=$BACKOFFICE_API_URL
      - API_DOCUMENT_ROOT=$BACKOFFICE_API_DOCUMENT_ROOT
    networks:
      default:
        ipv4_address: $BACKOFFICE_IP
        aliases:
          - $BACKOFFICE_URL
          - $BACKOFFICE_API_URL
  cdn:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $CDN_LOCAL:$CDN_DOCKER
    image: kaiocarvalhopravaler/apache:ubuntu16.04
    container_name: $CDN_CONTAINER
    extra_hosts:
      - "$CDN_URL:127.0.0.1"
    environment:
      - SITE_HOST=$CDN_URL
      - SITE_DOCUMENT_ROOT=${CDN_DOCKER}${CDN_DOCUMENT_ROOT}
      - VOLUME=$CDN_DOCKER
    networks:
      default:
        ipv4_address: $CDN_IP
        aliases:
          - $CDN_URL
  portal_pravaler:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $PORTALPRAVALER_LOCAL:$PORTALPRAVALER_DOCKER
    container_name: $PORTALPRAVALER_CONTAINER
    image: kaiocarvalhopravaler/php:5.6-apache
    extra_hosts:
      - "$PORTALPRAVALER_URL:127.0.0.1"
      - "qa.marketplace.idealinvest.srv.br:10.10.100.177"
    networks:
      default:
        ipv4_address: $PORTALPRAVALER_IP
        aliases:
          - $PORTALPRAVALER_URL
    environment:
      - VOLUME=$PORTALPRAVALER_DOCKER
      - SITE_HOST=$PORTALPRAVALER_URL
      - SITE_DOCUMENT_ROOT=${PORTALPRAVALER_DOCKER}${PORTALPRAVALER_DOCUMENT_ROOT}
  api_pravaler:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $APIPRAVALER_LOCAL:$APIPRAVALER_DOCKER
    container_name: $APIPRAVALER_CONTAINER
    image: kaiocarvalhopravaler/php:7.0-apache
    extra_hosts:
      - "$APIPRAVALER_URL:127.0.0.1"
    environment:
      - VOLUME=$APIPRAVALER_DOCKER
      - SITE_HOST=$APIPRAVALER_URL
      - SITE_DOCUMENT_ROOT=${APIPRAVALER_DOCKER}${APIPRAVALER_DOCUMENT_ROOT}
    networks:
      default:
        ipv4_address: $APIPRAVALER_IP
        aliases:
          - $APIPRAVALER_URL
  api_apartada:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
      - $APIAPARTADA_LOCAL:$APIAPARTADA_DOCKER
      - $BACKOFFICE_LOCAL:$BACKOFFICE_DOCKER
    container_name: $APIAPARTADA_CONTAINER
    image: kaiocarvalhopravaler/php:5.6-apache
    extra_hosts:
      - "$APIAPARTADA_URL:127.0.0.1"
    environment:
      - VOLUME=$APIAPARTADA_DOCKER
      - SITE_HOST=$APIAPARTADA_URL
      - SITE_DOCUMENT_ROOT=${APIAPARTADA_DOCKER}${APIAPARTADA_DOCUMENT_ROOT}
    networks:
      default:
        ipv4_address: $APIAPARTADA_IP
        aliases:
          - $APIAPARTADA_URL
  creditscore:
    volumes:
      - $CREDITSCORE_LOCAL:$CREDITSCORE_DOCKER
    container_name: $CREDITSCORE_CONTAINER
    image: kaiocarvalhopravaler/php:7.1-apache
    dns:
      - $DNS
    extra_hosts:
      - "$CREDITSCORE_URL:127.0.0.1"
    environment:
      - VOLUME=$CREDITSCORE_DOCKER
      - SITE_HOST=$CREDITSCORE_URL
      - SITE_DOCUMENT_ROOT=${CREDITSCORE_DOCKER}${CREDITSCORE_DOCUMENT_ROOT}
    networks:
      default:
        ipv4_address: $CREDITSCORE_IP
        aliases:
          - $CREDITSCORE_URL
  agendamento:
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - $AGENDAMENTO_LOCAL:$AGENDAMENTO_DOCKER
      - $BACKOFFICE_LOCAL:$BACKOFFICE_DOCKER
    container_name: $AGENDAMENTO_CONTAINER
    image: kaiocarvalhopravaler/php:7.2-apache
    dns:
      - $DNS
    extra_hosts:
      - "$AGENDAMENTO_URL:127.0.0.1"
    environment:
      - VOLUME=$AGENDAMENTO_DOCKER
      - SITE_HOST=$AGENDAMENTO_URL
      - SITE_DOCUMENT_ROOT=${AGENDAMENTO_DOCKER}${AGENDAMENTO_DOCUMENT_ROOT}
    networks:
      default:
        ipv4_address: $AGENDAMENTO_IP
        aliases:
          - $AGENDAMENTO_URL
  nginx:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    build:
      dockerfile: ./DockerFiles/Nginx/Dockerfile
      context: .
    container_name: nginx
    ports:
      - "80:80"
      - "9000:9000"
    networks:
      default:
        ipv4_address: $NGINX_IP
  mongodb:
    container_name: mongodb
    image: mongo:3.4
    restart: always
    dns:
      - $DNS
    networks:
      default:
        ipv4_address: $MONGODB_IP
  mongo-temp:
    container_name: mongo-temp
    dns:
      - $DNS
    build:
      dockerfile: ./DockerFiles/MongoDB/Dockerfile
      context: .
    restart: always
    networks:
      - default
    command: mongo "mongodb://mongodb" /data/db/script.js
    depends_on:
      - mongodb
  nova_proposta_frontend:
    restart: always
    stdin_open: true
    tty: true
    dns:
      - $DNS
    volumes:
       - $NOVAPROPOSTA_FRONTEND_LOCAL:$NOVAPROPOSTA_FRONTEND_DOCKER
    container_name: $NOVAPROPOSTA_FRONTEND_CONTAINER
    image: kaiocarvalhopravaler/angular:node-9
    extra_hosts:
      - "$NOVAPROPOSTA_FRONTEND_URL:127.0.0.1"
    environment:
      - VOLUME=$NOVAPROPOSTA_FRONTEND_DOCKER
      - ENVIRONMENT=dev
      - DOCUMENT_ROOT=$NOVAPROPOSTA_FRONTEND_DOCUMENT_ROOT
    networks:
      default:
        ipv4_address: $NOVAPROPOSTA_FRONTEND_IP
        aliases:
          - $NOVAPROPOSTA_FRONTEND_URL
  nova_proposta_backend:
    restart: always
    container_name: $NOVAPROPOSTA_BACKEND_CONTAINER
    image: kaiocarvalhopravaler/php:7.0-apache
    stdin_open: true
    tty: true
    dns:
      - $DNS
    environment:
      - VOLUME=$NOVAPROPOSTA_BACKEND_DOCKER
      - SITE_HOST=$NOVAPROPOSTA_BACKEND_URL
      - SITE_DOCUMENT_ROOT=${NOVAPROPOSTA_BACKEND_DOCKER}${NOVAPROPOSTA_BACKEND_DOCUMENT_ROOT}
    volumes:
      - $NOVAPROPOSTA_BACKEND_LOCAL:$NOVAPROPOSTA_BACKEND_DOCKER
    extra_hosts:
      - "$NOVAPROPOSTA_BACKEND_URL:127.0.0.1"
    networks:
       default:
          ipv4_address: $NOVAPROPOSTA_BACKEND_IP
          aliases:
            - $NOVAPROPOSTA_BACKEND_URL
    depends_on:
      - "mongo-temp"
      - "rabbitmq"
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    restart: always
    dns:
      - $DNS
    networks:
      - default
    environment:
      - RABBITMQ_ERLANG_COOKIE=9143a224982c82ae6985f3735bc95407
      - RABBITMQ_NODENAME=proposta-nova-node-1
  rabbitmq-management:
    image: rabbitmq:3-management
    restart: always
    container_name: rabbitmq-management
    networks:
      default:
        aliases:
          - $RABBITMQ_MANAGEMENT_URL
    environment:
      - RABBITMQ_DEFAULT_VHOST=$RABBITMQ_MANAGEMENT_URL
      - RABBITMQ_DEFAULT_USER=propostanova
      - RABBITMQ_DEFAULT_PASS=propostanova
    depends_on:
     - "rabbitmq"
  ftp_risco_cobranca:
    restart: always
    dns:
      - $DNS
    build:
      dockerfile: ./DockerFiles/FtpRiscoCobranca/Dockerfile
      context: .
    container_name: $FTPRISCOCOBRANCA_CONTAINER
    image: kaiocarvalhopravaler/ftp-risco-cobranca
    stdin_open: true
    volumes:
      - "/home/ftpusers/"
      - "/etc/pure-ftpd/passwd"
    environment:
      - PUBLICHOST=localhost
      - FTPRISCOCOBRANCA_BOLETOAVULSO_USER=$FTPRISCOCOBRANCA_BOLETOAVULSO_USER
      - FTPRISCOCOBRANCA_BOLETOAVULSO_PASSWORD=$FTPRISCOCOBRANCA_BOLETOAVULSO_PASSWORD
      - FTPRISCOCOBRANCA_IMPORTACAO_USER=$FTPRISCOCOBRANCA_IMPORTACAO_USER
      - FTPRISCOCOBRANCA_IMPORTACAO_PASSWORD=$FTPRISCOCOBRANCA_IMPORTACAO_PASSWORD
    tty: true
    networks:
      default:
        ipv4_address: $FTPRISCOCOBRANCA_IP
        aliases:
          - $FTPRISCOCOBRANCA_URL
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
  seguros:
    restart: always
    container_name: $SEGUROS_CONTAINER
    image: kaiocarvalhopravaler/php:7.1-apache
    stdin_open: true
    tty: true
    dns:
      - $DNS
    environment:
      - VOLUME=$SEGUROS_DOCKER
      - SITE_HOST=$SEGUROS_URL
      - SITE_DOCUMENT_ROOT=${SEGUROS_DOCKER}${SEGUROS_DOCUMENT_ROOT}
    volumes:
      - $SEGUROS_LOCAL:$SEGUROS_DOCKER
    extra_hosts:
      - "$SEGUROS_URL:127.0.0.1"
    networks:
       default:
          ipv4_address: $SEGUROS_IP
          aliases:
            - $SEGUROS_URL
  marketplace_api:
      restart: always
      container_name: $MARKETPLACE_API_CONTAINER
      image: kaiocarvalhopravaler/php:7.1-apache
      stdin_open: true
      tty: true
      dns:
        - $DNS
      environment:
        - VOLUME=$MARKETPLACE_API_DOCKER
        - SITE_HOST=$MARKETPLACE_API_URL
        - SITE_DOCUMENT_ROOT=${MARKETPLACE_API_DOCKER}${MARKETPLACE_API_DOCUMENT_ROOT}
      volumes:
        - $MARKETPLACE_API_LOCAL:$MARKETPLACE_API_DOCKER
      extra_hosts:
        - "$MARKETPLACE_API_URL:127.0.0.1"
      depends_on:
        - redis
      networks:
         default:
            ipv4_address: $MARKETPLACE_API_IP
            aliases:
              - $MARKETPLACE_API_URL
  retornomec:
    restart: always
    container_name: $RETORNO_MEC_CONTAINER
    stdin_open: true
    tty: true
    image: kaiocarvalhopravaler/php:7.1-apache
    dns:
      - $DNS
    environment:
      - VOLUME=$RETORNO_MEC_DOCKER
      - SITE_HOST=$RETORNO_MEC_URL
      - SITE_DOCUMENT_ROOT=${RETORNO_MEC_DOCKER}${RETORNO_MEC_DOCUMENT_ROOT}
    volumes:
      - $RETORNO_MEC_LOCAL:$RETORNO_MEC_DOCKER
    extra_hosts:
      - "$RETORNO_MEC_URL:127.0.0.1"
    depends_on:
      - redis
    networks:
       default:
          ipv4_address: $RETORNO_MEC_IP
          aliases:
            - $RETORNO_MEC_URL
  redis:
    build:
      dockerfile: ./DockerFiles/Backoffice/Dockerfile
      context: .
    container_name: redis
    networks:
      - default