FROM kaioidealinvest/php5.6

COPY DockerFiles/PortalPravaler/Files/portalpravaler.idealinvest.homologacao01.conf /etc/apache2/sites-available/ 

RUN a2ensite portalpravaler.idealinvest.homologacao01.conf